# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20161028_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_pic',
            new_name='photo',
        ),
    ]
