# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20161026_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_address',
            name='name',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping_address',
            name='name',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
