# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20161027_0105'),
        ('users', '0003_order_products'),
    ]

    operations = [
    ]
