# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ship_to',
        ),
    ]
