# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_order_ship_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_products',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='order_products',
            old_name='product_id',
            new_name='product',
        ),
    ]
